# Generated by Django 4.2.2 on 2023-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=0, max_length=25)),
                ('door_open', models.BooleanField(default=False)),
                ('maintainence', models.BooleanField(default=False)),
                ('move_up', models.BooleanField(default=False)),
                ('move_down', models.BooleanField(default=False)),
                ('group_number', models.IntegerField()),
            ],
        ),
    ]
