# Generated by Django 3.2.7 on 2023-06-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_elevator_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='group_number',
            field=models.CharField(max_length=20),
        ),
    ]
