# Generated by Django 4.2.2 on 2023-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_elevator_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='total_floors',
            field=models.IntegerField(default=1),
        ),
    ]
