# Generated by Django 4.2.2 on 2023-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_elevator_total_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
