# Generated by Django 4.2.2 on 2023-06-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_elevator_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='move_down',
            new_name='in_motion',
        ),
    ]
